 (define (parse-word word-list) 
    (define (random-element l)
        (if (null? l)
            (amb)
            (amb (car l) (random-element (cdr l)))))
    (require (not (null? *unparsed*))) 
    (require (memq (car *unparsed*) (cdr word-list))) 
    (let ((found-word (car *unparsed*))) 
        (set! *unparsed* (cdr *unparsed*)) 
        (random-element (cdr word-list))))  